### ISSUE TITLE
Audio mezzanines missing from mezzanine pool

### ISSUE THREAD

**Issue by yanj-github** [cta-wave/mezzanine#48]
Use of audio watermarks hasn't get fully agreed and audio source mezzanines are missing from mezzanine pool.
As it mentioned on https://github.com/cta-wave/mezzanine/issues/41, currently there are 4 PN audio watermarks on the water mark study repo but which wasn't get uploaded to the mezzanine pool.

**Comment by yanj-github** [comment]
In accordance with issue https://github.com/cta-wave/dpctf-tests/issues/56, it is required to reduce the audio stream duration from 60s to 30s for most of the tests. Do we need a 30s audio mezzanine?

**Comment by yanj-github** [comment]
How about? 

- PN01 30 seconds - base mezzanine
- PN02 unchanged 60 seconds - spare - can be used for swithing test if is required
- PN03 unchanged 60 seconds - splicing main
- PN04 30 seconds - splicing ad
- AdagioPN01-12dB.wav - 60 seconds unchanged but do we still need this? Maybe worth keep it there anyway.

@cta-source I dont have permission to access akamai pool, so sorry wont be able to help with upload. 
But we should delay it anyway until we agreed with the duration.

**Comment by yanj-github** [comment]
Hi @jpiesing  and @cta-source do you agree what has been proposed above please?
PN02 and PN03 are unchanged and PN01 and PN04 to reduced to 30 seconds in duration.

**Comment by cta-source** [comment]
Sorry, just seeing the proposal now. Is it necessary to reduce the PN files in length? Can't we keep them long and use a subset as needed?  

The Adagio file was a demo, we don't need it as part of the Mezzanine content in my opinion. But it may be nice to have around for test purposes, so I agree, maybe it's worth keeping there anyway.

**Comment by jpiesing** [comment]
> Sorry, just seeing the proposal now. Is it necessary to reduce the PN files in length? Can't we keep them long and use a subset as needed?

The tools and scripting may be simpler if we can just use a 30s file "as-is" rather than cutting it.

**Comment by jpiesing** [comment]
I wonder what audio durations are needed for 9.4 "Splicing of WAVE Program with Baseline Constraints"?
The segment durations for splicing are very carefully chosen to also work for audio - https://github.com/cta-wave/mezzanine/issues/40 .

**Comment by cta-source** [comment]
Files are available and ready to be uploaded to the mezzanine pool. (Extensive) details follow. 

.....

The audio watermark repo is at [https://github.com/cta-source/audio-watermark-study](https://github.com/cta-source/audio-watermark-study). I’ve updated this repo with the new (trimmed) audio white noise files.

The new files are in a subfolder, [./syncsupport/Second PN release 2022-03-23 - PN0nv02](https://github.com/cta-source/audio-watermark-study/tree/main/syncsupport/src/Second%20PN%20release%202022-03-23%20-%20PN0nv02).

Here is the precis, which is also in README.TXT in the subfolder: 

> Files included in the audio whitenoise release: "Second PN release 2022-03-23 - PN0nv02"
> 
> The key for generating each sequence is of the form "PNnn", e.g., "PN01", "PN02", etc.  
> 
> * PN01v02 (key "PN01") 30 seconds - base mezzanine
> * PN02v02 (key "PN02") 60 seconds - spare - can be used for switching test if required
> * PN03v02 (key "PN03") 60 seconds - splicing main
> * PN04v02 (key "PN01") 30 seconds - splicing ad
> * AdagioPN01-12dB.wav - A recording of Samuel Barber's "Adagio for Strings" at (approximately) full scale in the left channel, with a 60s PN01 (12dB down from full scale) in the right channel. Length 60 seconds; this file is unchanged from the first release. Typically not used, but retained for occasional ad hoc debugging. Demonstrates ability to extract valid mediaTime at 20mS periods despite larger music power.

As background, the following issues touch on definition of these files:
•	“Audio mezzanines missing from mezzanine pool #48”. This issue includes Yan’s proposal for lengths and some discussion.
•	“WAVE Splice: fractional framerate (14.985, 29.97, 59.94) CMAF Fragment duration considerations #40”. I don’t see an impact or overlap from this analysis to these durations. 
•	“Update some tests to use 20s or 30s content rather than 60s [#56](https://github.com/cta-wave/dpctf-tests/issues/56)”. Appears to be OBE with mezzanine issue #48 decisions.
•	“MPEG audio codec options to be tested [#27](https://github.com/cta-wave/Test-Content/issues/27)”. Discusses lengths. Appears to be OBE with mezzanine issue #48 decisions.
•	“Consider making length of DPCTF tests a session option #34”. (Enhancement) The current version (Oct. 2021) of the syncsupport code (i.e., the audio watermarking code for WAVE) supports lengths less than the PN file length; that is, the length of the PN file is not critical to the code as long as it’s long enough to cover the requested test interval. This enhancement would not be difficult to handle with the syncsupport code and doesn’t impact these file lengths.

I believe the list above, which is exactly what @yanj-github proposed, either fits the requirements in these Issues or doesn't conflict with anything there.

@nicholas-fr, these files can be moved from the audio white noise repo to the mezzanine pool. At that point we can close this issue.

**Comment by nicholas-fr** [comment]
The audio mezzanine files from [./syncsupport/Second PN release 2022-03-23 - PN0nv02](https://github.com/cta-source/audio-watermark-study/tree/main/syncsupport/src/Second%20PN%20release%202022-03-23%20-%20PN0nv02) have been copied to the mezzanine pool here, based on the agreed conventions regarding mezzanine releases:
http://dash-large-files.akamaized.net/WAVE/Mezzanine/under_review/2022-04-01/

They'll normally be part of the next mezzanine release we approve i.e. 3, but they're already available for use in the meantime.
