### ISSUE TITLE
fault in mezzanine QR code

### ISSUE THREAD

**Issue by yanj-github** [cta-wave/mezzanine#50]
The last mezzanine QR code reports 00:60:00 instead of 01:00:00.
I remember this issue has been corrected before but it seems the issue is back again.
OF won't take 00:60:00 as a valid time data.

**Comment by nicholas-fr** [comment]
Thanks for raising this @yanj-github , I believe only the 30fps streams have this issue, could you confirm that's also what you see?
I have a fix and will upload corrected mezzanine streams this week.

**Comment by yanj-github** [comment]
@nicholas-fr I will have a look, can I have the link to the latest mezzanine please?

**Comment by nicholas-fr** [comment]
Thanks @yanj-github, I thought you noticed the issue when using the test content, so I was wondering in which content you'd seen it.
I have a fix for the issue and will create a pull request for the script. 
I uploaded new 30fps mezzanine with the fix here: https://dash.akamaized.net/WAVE/Mezzanine/under_review/2022-08-16/

Here is an overview of the mezzanine streams...
   
Latest mezzanine  release:
  - https://dash.akamaized.net/WAVE/Mezzanine/releases/2/

Additional changes for next release (3):
 - Fixed QR code of last frame (1800) in 30fps 60 second mezzanine streams (timestamp now correctly contains 00:01:00.000 instead of 00:00:60.000)
    - https://dash.akamaized.net/WAVE/Mezzanine/under_review/2022-08-16/
 - Added 30s mezzanine streams to reduce testing time
    - https://dash.akamaized.net/WAVE/Mezzanine/under_review/2022-04-21/
 - Added 2h mezzanine streams for long duration tests
    - https://dash.akamaized.net/WAVE/Mezzanine/under_review/2022-07-20/
 - Audio
    - https://dash.akamaized.net/WAVE/Mezzanine/under_review/2022-07-20/

**Comment by yanj-github** [comment]
> Thanks @yanj-github, I thought you noticed the issue when using the test content, so I was wondering in which content you'd seen it.
Yes I have noticed issue when running tests on test runner. 
Please find detail here https://github.com/cta-wave/dpctf-tests/blob/dpcat/tests.csv
Streams on date 2022-01-17 are used.

**Comment by yanj-github** [comment]
> I uploaded new 30fps mezzanine with the fix here: https://dash.akamaized.net/WAVE/Mezzanine/under_review/2022-08-16/

I just done a random check of 2-3 stream on here they seems fine.

**Comment by yanj-github** [comment]
@nicholas-fr  I have checked this on https://dash.akamaized.net/WAVE/Mezzanine/releases/3 just one file and it looks good to me. QR code at the end reports correct 01:00:00.
I think this issue now is to regeneration of test content using lastest mezzanine and further link correctly to TR.
if @rbouqueau and @louaybassbouss have this in the agenda already I will close this issue. Let me know if this is fine please?
Just one sugguestion @nicholas-fr  it would be better to remove the faulty mezzanine or moev it to to be deleted folder it would prevent futher faults.
